# Análise de dados com Python

## Desafio

1. Importar a base de dados
1. Visuallizar a base de dados
    - Entender quais as informações estão disponíveis
    - Descobrir os erros da base de dados
1. Tratar os dados
    - Valores reconhecidos de forma errada
1. Análise Inicial
1. Análise mais completa

In [4]:
# Importando a biblioteca pandas
import pandas as pd
# Importando a base de dados
tabela = pd.read_csv('datas/telecom_users.csv')
# Visualisar a base de dados
display(tabela)

,Unnamed: 0,IDCliente,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,...,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn,Codigo
0,1869,7010-BRBUU,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,...,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao,NaN
1,4528,9688-YGXVR,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,...,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.2,Nao,NaN
2,6344,9286-DOJGF,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,...,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim,NaN
3,6739,6994-KERXL,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,...,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.5,Nao,NaN
4,432,2181-UAESM,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,...,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.5,Nao,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,3772,0684-AOSIH,Masculino,0,Sim,Nao,1,Sim,Nao,Fibra,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,95.00,95,Sim,NaN
5982,5191,5982-PSMKW,Feminino,0,Sim,Sim,23,Sim,Sim,DSL,...,Sim,Sim,Sim,2 anos,Sim,CartaoCredito,91.10,2198.3,Nao,NaN
5983,5226,8044-BGWPI,Masculino,0,Sim,Sim,12,Sim,Nao,Nao,...,SemInternet,SemInternet,SemInternet,Mensal,Sim,BoletoEletronico,21.15,306.05,Nao,NaN
5984,5390,7450-NWRTR,Masculino,1,Nao,Nao,12,Sim,Sim,Fibra,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,99.45,1200.15,Sim,NaN
5985,860,4795-UXVCJ,Masculino,0,Nao,Nao,26,Sim,Nao,Nao,...,SemInternet,SemInternet,SemInternet,Anual,Nao,CartaoCredito,19.80,457.3,Nao,NaN

In [21]:
print(tabela['Genero'].value_counts())
print((tabela['Genero'].value_counts() / len(tabela['Genero'])) * 100)

Masculino    3050
Feminino     2936
Name: Genero, dtype: int64
Masculino    50.952222
Feminino     49.047778
Name: Genero, dtype: float64

In [22]:
print(tabela['ServicoInternet'].value_counts())
print((tabela['ServicoInternet'].value_counts() / len(tabela['ServicoInternet'])) * 100)

Fibra    2627
DSL      2068
Nao      1291
Name: ServicoInternet, dtype: int64
Fibra    43.885733
DSL      34.547277
Nao      21.566990
Name: ServicoInternet, dtype: float64

In [23]:
print(tabela['TipoContrato'].value_counts())
print((tabela['TipoContrato'].value_counts() / len(tabela['TipoContrato'])) * 100)

Mensal    3269
2 anos    1441
Anual     1276
Name: TipoContrato, dtype: int64
Mensal    54.610758
2 anos    24.072837
Anual     21.316405
Name: TipoContrato, dtype: float64

In [24]:
print(tabela['FormaPagamento'].value_counts())
print((tabela['FormaPagamento'].value_counts() / len(tabela['FormaPagamento'])) * 100)

BoletoEletronico    2006
BoletoImpresso      1369
DebitoAutomatico    1308
CartaoCredito       1303
Name: FormaPagamento, dtype: int64
BoletoEletronico    33.511527
BoletoImpresso      22.870030
DebitoAutomatico    21.850986
CartaoCredito       21.767457
Name: FormaPagamento, dtype: float64

In [28]:
print(tabela['Churn'].value_counts())
print((tabela['Churn'].value_counts() / len(tabela['Churn'])) * 100)

Nao    4398
Sim    1587
Name: Churn, dtype: int64
Nao    73.471433
Sim    26.511861
Name: Churn, dtype: float64

In [29]:
tabela = tabela.drop('Unnamed: 0', axis=1)
display(tabela)

,IDCliente,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,ServicoSegurancaOnline,...,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn,Codigo
0,7010-BRBUU,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao,NaN
1,9688-YGXVR,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,Nao,...,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.2,Nao,NaN
2,9286-DOJGF,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,Nao,...,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim,NaN
3,6994-KERXL,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,Nao,...,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.5,Nao,NaN
4,2181-UAESM,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,Sim,...,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.5,Nao,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,0684-AOSIH,Masculino,0,Sim,Nao,1,Sim,Nao,Fibra,Sim,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,95.00,95,Sim,NaN
5982,5982-PSMKW,Feminino,0,Sim,Sim,23,Sim,Sim,DSL,Sim,...,Sim,Sim,Sim,2 anos,Sim,CartaoCredito,91.10,2198.3,Nao,NaN
5983,8044-BGWPI,Masculino,0,Sim,Sim,12,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,Mensal,Sim,BoletoEletronico,21.15,306.05,Nao,NaN
5984,7450-NWRTR,Masculino,1,Nao,Nao,12,Sim,Sim,Fibra,Nao,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,99.45,1200.15,Sim,NaN
5985,4795-UXVCJ,Masculino,0,Nao,Nao,26,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,Anual,Nao,CartaoCredito,19.80,457.3,Nao,NaN

In [33]:
print(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 22 columns):
IDCliente                 5986 non-null object
Genero                    5986 non-null object
Aposentado                5986 non-null int64
Casado                    5986 non-null object
Dependentes               5985 non-null object
MesesComoCliente          5986 non-null int64
ServicoTelefone           5986 non-null object
MultiplasLinhas           5986 non-null object
ServicoInternet           5986 non-null object
ServicoSegurancaOnline    5986 non-null object
ServicoBackupOnline       5986 non-null object
ProtecaoEquipamento       5986 non-null object
ServicoSuporteTecnico     5986 non-null object
ServicoStreamingTV        5986 non-null object
ServicoFilmes             5986 non-null object
TipoContrato              5986 non-null object
FaturaDigital             5986 non-null object
FormaPagamento            5986 non-null object
ValorMensal               5986 non-null float64
TotalGasto                5986 non-null object
Churn                     5985 non-null object
Codigo                    0 non-null float64
dtypes: float64(2), int64(2), object(18)
memory usage: 1.0+ MB
None

In [53]:
tabela['TotalGasto'] = pd.to_numeric(tabela['TotalGasto'], errors='coerce') # <errors='coerce '> resolve proplemas de forma padrão

In [54]:
print(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 23 columns):
IDCliente                 5986 non-null object
Genero                    5986 non-null object
Aposentado                5986 non-null int64
Casado                    5986 non-null object
Dependentes               5985 non-null object
MesesComoCliente          5986 non-null int64
ServicoTelefone           5986 non-null object
MultiplasLinhas           5986 non-null object
ServicoInternet           5986 non-null object
ServicoSegurancaOnline    5986 non-null object
ServicoBackupOnline       5986 non-null object
ProtecaoEquipamento       5986 non-null object
ServicoSuporteTecnico     5986 non-null object
ServicoStreamingTV        5986 non-null object
ServicoFilmes             5986 non-null object
TipoContrato              5986 non-null object
FaturaDigital             5986 non-null object
FormaPagamento            5986 non-null object
ValorMensal               5986 non-null float64
TotalGasto                5976 non-null float64
Churn                     5985 non-null object
Codigo                    0 non-null float64
TotalGasto_valor          5986 non-null bool
dtypes: bool(1), float64(3), int64(2), object(17)
memory usage: 1.0+ MB
None

In [ ]:
tabela = tabela.dropna(how='all', axis=1)
tabela = tabela.dropn